### ISSUE TITLE
Build error on Meteor 1.2.0.2

### ISSUE THREAD

**Issue by JeremySaks** [kadirahq/meteor-dochead#12]
Trying to run `meteor` on the new version 1.2.0.2 with `kadira:dochead@1.2.0` results in the following:

```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with cosmos:browserify (for target web.browser):
   packages/kadira:dochead/package.browserify.js: Arguments to path.resolve must be strings

   While processing files with cosmos:browserify (for target web.cordova):
   packages/kadira:dochead/package.browserify.js: Arguments to path.resolve must be strings

=> Your application has errors. Waiting for file change.
```

**Comment by kokjinsam** [comment]
+1

**Comment by krstffr** [comment]
+1

**Comment by TimFletcher** [comment]
I believe this is a duplicate of #11.

I'm having the same issue which I resolved by editing my `meteor/.versions` file to move back to version `1.1.0`.

**Comment by arunoda** [comment]
I got this issue too and disappear somehow. Not sure why.
Anyway, I updated the browserify version and published a new version. (1.2.1)

If you got this again, may be you can remove `.meteor/local` directory and try again.

Hope all you guys are using Meteor 1.2

**Comment by krstffr** [comment]
@arunoda sorry, removing .meteor/local does not fix it.

Still getting:

```
While processing files with cosmos:browserify (for target web.browser):
   packages/kadira:dochead/package.browserify.js: Arguments to path.resolve must be strings
```

**Comment by arunoda** [comment]
Okay. Let me get some help from a help from a specialist.

**Comment by krstffr** [comment]
@arunoda you guys are the best! :+1:

**Comment by elidoran** [comment]
This error is, unfortunately, my fault. Please update to cosmos:browserify 0.8.0. Versions 0.7.1 through 0.7.4 are broken. They are attempts to make it work properly for all the variations there are, and, it fails to do so. 

The new Build API of Meteor 1.2 is wreaking havoc on my plugin because it no longer provides actual directory location information, and, it builds the packages in more places. packages are now published in an _unbuilt_ format and require building by a plugin from their location in ~/.meteor/packages, which also puts the npm modules into _npm_ instead of _.npm/package_.

Essentially, [this](https://github.com/elidoran/cosmos-browserify/blob/52b30fdaefc84aea7438708d936d37ec392443e6/plugin/browserify.coffee#L142), fairly simple two steps, has become [this](https://github.com/elidoran/cosmos-browserify/blob/master/plugin/browserify.coffee#L45), deep property inspection. 

Any recommendations for improving it are appreciated.

**Comment by JeremySaks** [comment]
`meteor update cosmos:browserify` and re-adding dochead does the trick!

**Comment by arunoda** [comment]
Thanks @elidoran I'll update it.
Not sure any recommendations.

**Comment by arunoda** [comment]
I published the new version. Hopefully it should fix this issue.

**Comment by TimFletcher** [comment]
Seems good for me. Thanks!

**Comment by bmanturner** [comment]
Not fixed on Windows 7

> While processing files with cosmos:browserify (for target web.browser): packages/kadira:dochead/package.browserify.js: Cannot find module 'load-script' from '\C\Users\bmanturner\AppData\Local\.meteor\packages\kadira_dochead\1.2.2\npm'

**Note:** The directory of the application is located in C\Users\bmanturner\Documents, not AppData.

**Comment by elidoran** [comment]
The kadira:dochead package is stored in AppData when you add it to an app via `meteor add kadira:dochead`.

I see a possible cause. It looks like I need to do `Plugin.convertToOSPath()` to convert the property from the *nix style path (used internally everywhere by Meteor) to the windows style path. I'll patch it later today.
